# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""Generate the conveyor_sort textures, UV-mapped visual meshes and item pool XML.

Every textured surface is a mesh with UV coordinates and a 2D texture. That is
the only textured case both MuJoCo's renderer (the camera streams) and the
mjviser browser viewer draw; mjviser renders primitives with a flat color and
reduces cube maps to one color per face.
"""  # noqa: INP001

from __future__ import annotations

import struct
import zlib
from pathlib import Path

import numpy as np

from physicalai_mujoco_so101_plugin.conveyor import ITEM_COLORS as ITEM_COLOR_NAMES
from physicalai_mujoco_so101_plugin.conveyor import pool_item_names

OUT = Path(__file__).resolve().parent.parent / "urdf" / "scenes" / "conveyor_sort" / "assets"

# Item texture colors (sRGB 0-255). Names must match conveyor.ITEM_COLORS; keep the RGB values in
# sync with the item materials in conveyor_sort/scene.xml.
ITEM_COLORS: dict[str, tuple[int, int, int]] = {
    "red": (204, 30, 30),
    "blue": (30, 80, 220),
    "green": (40, 165, 55),
    "purple": (140, 55, 180),
}

CRACK_RGB = (15, 12, 10)
SKIN_PX = 128
BELT_PX = 64

ITEM_HALF = 0.015  # 3 cm items
ITEM_MASS = 0.02
# Free-joint damping: kills the endless coin-like wobble of cylinders in a bin (angular decay
# ~15 ms) while barely touching translation (linear decay ~100 s, far below belt friction).
ITEM_DAMPING = 0.0002
# Unused pool items wait in the lidded supply crate behind the robot (see scene.xml):
# a 4 x 6 grid, outside the arm's +-110 deg pan range and the overview camera view.
PARK_ORIGIN = (-0.4175, -0.1125)
PARK_SPACING = 0.045
PARK_COLUMNS = 4
PARK_Z = 0.0215  # resting on the crate floor (top at z = 0.006)

HEX_RADIUS = 0.016  # circumradius; keep in sync with the hex_prism collision mesh in scene.xml
CYLINDER_SEGMENTS = 32
CYLINDER_SKIN_REPEATS = 3  # crack skin repeats around the cylinder, so tiles stay about square
BELT_HALF = (0.04, 0.41, 0.005)  # keep in sync with the conveyor_belt geom in scene.xml
BELT_TILE = 0.02  # keep in sync with conveyor.BELT_TILE

# Bin labels: a white plate on each bin floor, text facing the standard overview camera.
LABEL_HALF = (0.02, 0.043, 0.0004)  # x (text height), y (text width), z; metres
LABEL_PX = (300, 140)  # width, height; same aspect as the plate
LABELS: dict[str, tuple[str, tuple[int, int, int]]] = {
    "red": ("RED", (204, 30, 30)),
    "blue": ("BLUE", (30, 80, 220)),
    "green": ("GREEN", (40, 165, 55)),
    "reject": ("REJECT", (230, 180, 20)),
}
# 5 x 7 bitmap glyphs for the label text; generated PNGs are identical on every machine.
_GLYPHS = {
    "B": ("11110", "10001", "10001", "11110", "10001", "10001", "11110"),
    "C": ("01110", "10001", "10000", "10000", "10000", "10001", "01110"),
    "D": ("11110", "10001", "10001", "10001", "10001", "10001", "11110"),
    "E": ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    "G": ("01110", "10001", "10000", "10111", "10001", "10001", "01111"),
    "J": ("00111", "00010", "00010", "00010", "00010", "10010", "01100"),
    "L": ("10000", "10000", "10000", "10000", "10000", "10000", "11111"),
    "N": ("10001", "11001", "10101", "10011", "10001", "10001", "10001"),
    "R": ("11110", "10001", "10001", "11110", "10100", "10010", "10001"),
    "T": ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
    "U": ("10001", "10001", "10001", "10001", "10001", "10001", "01110"),
}


def items_xml() -> str:
    """MJCF for the item pool, included by conveyor_sort/scene.xml."""
    lines = [
        "<?xml version=\"1.0\"?>",
        "<!-- Generated by scripts/generate_conveyor_assets.py; do not edit by hand. -->",
        "<conveyor_items>",
    ]
    h = ITEM_HALF
    for idx, name in enumerate(pool_item_names()):
        _, shape, color, *rest = name.split("_")
        material = f"item_{color}{'_cracked' if rest else ''}"
        x = PARK_ORIGIN[0] + (idx % PARK_COLUMNS) * PARK_SPACING
        y = PARK_ORIGIN[1] + (idx // PARK_COLUMNS) * PARK_SPACING
        if shape == "cube":
            geom = f'type="box" size="{h} {h} {h}"'
        elif shape == "cylinder":
            geom = f'type="cylinder" size="{h} {h}"'
        else:
            geom = 'type="mesh" mesh="hex_prism"'
        lines += [
            f'  <body name="{name}" pos="{x:.4f} {y:.4f} {PARK_Z}">',
            f'    <joint type="free" name="{name}:joint" damping="{ITEM_DAMPING}" frictionloss="0" armature="0"/>',
        ]
        if rest:
            # Cracked: an invisible collision primitive (first, so it defines the item) plus a
            # UV-mapped visual mesh that carries the crack texture.
            lines += [
                f'    <geom name="{name}" class="conveyor_item" {geom} mass="{ITEM_MASS}" group="3" rgba="0 0 0 0"/>',
                f'    <geom class="conveyor_item_skin" mesh="skin_{shape}" material="{material}"/>',
            ]
        else:
            lines.append(f'    <geom name="{name}" class="conveyor_item" {geom} material="{material}" mass="{ITEM_MASS}"/>')
        lines.append("  </body>")
    lines.append("</conveyor_items>")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# UV-mapped meshes
# ---------------------------------------------------------------------------

# Box face tangents (u, v) with u x v = outward normal, so quads wind counter-clockwise.
_BOX_FACES = (
    ((0, 0, 1), (1, 0, 0), (0, 1, 0)),
    ((0, 0, -1), (0, 1, 0), (1, 0, 0)),
    ((1, 0, 0), (0, 1, 0), (0, 0, 1)),
    ((-1, 0, 0), (0, 0, 1), (0, 1, 0)),
    ((0, 1, 0), (0, 0, 1), (1, 0, 0)),
    ((0, -1, 0), (1, 0, 0), (0, 0, 1)),
)


class _Mesh:
    """Triangles with per-corner UVs, written as OBJ (``f v/vt``)."""

    def __init__(self) -> None:
        self.verts: list[tuple[float, float, float]] = []
        self.uvs: list[tuple[float, float]] = []
        self.faces: list[tuple[int, int, int]] = []

    def add(self, vert: np.ndarray, uv: tuple[float, float]) -> int:
        self.verts.append(tuple(float(c) for c in vert))
        self.uvs.append((float(uv[0]), float(uv[1])))
        return len(self.verts) - 1

    def quad(self, corners: list[np.ndarray], uvs: list[tuple[float, float]]) -> None:
        a, b, c, d = (self.add(v, uv) for v, uv in zip(corners, uvs, strict=True))
        self.faces += [(a, b, c), (a, c, d)]

    def write(self, path: Path) -> None:
        lines = ["# Generated by scripts/generate_conveyor_assets.py"]
        lines += [f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in self.verts]
        lines += [f"vt {u:.6f} {v:.6f}" for u, v in self.uvs]
        lines += [f"f {a + 1}/{a + 1} {b + 1}/{b + 1} {c + 1}/{c + 1}" for a, b, c in self.faces]
        path.write_text("\n".join(lines) + "\n")


def box_mesh(half: tuple[float, float, float], tile: float | None = None) -> _Mesh:
    """A box; each face shows the whole texture, or repeats it every `tile` metres."""
    mesh = _Mesh()
    half_arr = np.asarray(half)
    for normal, u_axis, v_axis in _BOX_FACES:
        n, u, v = (np.asarray(a, dtype=np.float64) for a in (normal, u_axis, v_axis))
        centre = n * half_arr
        hu, hv = float(u @ half_arr), float(v @ half_arr)
        corners, uvs = [], []
        for su, sv in ((-1, -1), (1, -1), (1, 1), (-1, 1)):
            corners.append(centre + su * hu * u + sv * hv * v)
            if tile is None:
                uvs.append(((su + 1) / 2, (sv + 1) / 2))
            else:
                uvs.append((su * hu / tile, sv * hv / tile))
        mesh.quad(corners, uvs)
    return mesh


def prism_mesh(radius: float, half_height: float, segments: int, u_per_segment: float) -> _Mesh:
    """An upright prism (a cylinder for many segments) with a UV-wrapped side and planar caps."""
    mesh = _Mesh()
    angles = np.linspace(0.0, 2.0 * np.pi, segments + 1)
    ring = [np.array([radius * np.cos(a), radius * np.sin(a), 0.0]) for a in angles]
    up = np.array([0.0, 0.0, half_height])
    for i in range(segments):
        u0, u1 = i * u_per_segment, (i + 1) * u_per_segment
        mesh.quad([ring[i] - up, ring[i + 1] - up, ring[i + 1] + up, ring[i] + up], [(u0, 0), (u1, 0), (u1, 1), (u0, 1)])

    def cap_uv(p: np.ndarray) -> tuple[float, float]:
        return (p[0] / (2 * radius) + 0.5, p[1] / (2 * radius) + 0.5)

    for sign in (1, -1):
        centre = mesh.add(sign * up, (0.5, 0.5))
        for i in range(segments):
            a, b = ring[i] + sign * up, ring[i + 1] + sign * up
            ia, ib = mesh.add(a, cap_uv(a)), mesh.add(b, cap_uv(b))
            mesh.faces.append((centre, ia, ib) if sign > 0 else (centre, ib, ia))
    return mesh


def label_mesh() -> _Mesh:
    """A thin plate whose top face reads upright from the standard overview camera.

    That camera looks along +x, so text runs along -y (image left to right) and
    its up direction is +x. The other faces sample the plate's white margin.
    """
    hx, hy, hz = LABEL_HALF
    mesh = box_mesh(LABEL_HALF)
    # Drop the box's own top face (the first quad): a second face in the same plane z-fights with
    # the text face, which flickers in close-up views such as the wrist camera.
    mesh.verts, mesh.uvs, mesh.faces = mesh.verts[4:], [(0.5, 0.03)] * (len(mesh.verts) - 4), [
        (a - 4, b - 4, c - 4) for a, b, c in mesh.faces[2:]
    ]
    top = [np.array(c) for c in ((-hx, hy, hz), (-hx, -hy, hz), (hx, -hy, hz), (hx, hy, hz))]
    mesh.quad(top, [(0, 0), (1, 0), (1, 1), (0, 1)])
    return mesh


def label_texture(text: str, border_rgb: tuple[int, int, int]) -> np.ndarray:
    """White plate, colored border, bold dark text."""
    w, h = LABEL_PX
    img = np.full((h, w, 3), 242, dtype=np.uint8)
    border = 8
    img[:border], img[-border:], img[:, :border], img[:, -border:] = border_rgb, border_rgb, border_rgb, border_rgb
    scale = 7  # REJECT (35 glyph columns) fills the plate at this scale
    bold = 2
    cols = 6 * len(text) - 1
    x0, y0 = (w - cols * scale) // 2, (h - 7 * scale) // 2
    for i, ch in enumerate(text):
        for row, bits in enumerate(_GLYPHS[ch]):
            for col, bit in enumerate(bits):
                if bit == "1":
                    x = x0 + (6 * i + col) * scale
                    y = y0 + row * scale
                    # Blocks overlap by `bold` px so strokes survive downscaling in the camera views.
                    img[y - bold : y + scale + bold, x - bold : x + scale + bold] = (25, 25, 25)
    return img


def write_meshes() -> None:
    """Write the UV-mapped visual meshes for cracked items and the belt surface."""
    h = ITEM_HALF
    box_mesh((h, h, h)).write(OUT / "skin_cube.obj")
    prism_mesh(h, h, CYLINDER_SEGMENTS, CYLINDER_SKIN_REPEATS / CYLINDER_SEGMENTS).write(OUT / "skin_cylinder.obj")
    prism_mesh(HEX_RADIUS, h, 6, 1.0).write(OUT / "skin_hex.obj")
    box_mesh(BELT_HALF, tile=BELT_TILE).write(OUT / "belt_surface.obj")
    label_mesh().write(OUT / "bin_label.obj")


def _write_png(path: Path, data: np.ndarray) -> None:
    """Write an 8-bit RGB array as a PNG without third-party imaging libraries."""
    h, _w, _channels = data.shape
    raw = b"".join(b"\x00" + data[y].tobytes() for y in range(h))

    def chunk(ctype: bytes, cdata: bytes) -> bytes:
        c = ctype + cdata
        return struct.pack(">I", len(cdata)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", data.shape[1], h, 8, 2, 0, 0, 0)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    path.write_bytes(png)


def _stamp_polyline(img: np.ndarray, points: np.ndarray, radius: float, rgb: tuple[int, int, int]) -> None:
    """Draw a thick polyline by stamping discs along each segment."""
    h, w, _ = img.shape
    yy, xx = np.mgrid[0:h, 0:w]
    mask = np.zeros((h, w), dtype=bool)
    for (x0, y0), (x1, y1) in zip(points[:-1], points[1:], strict=True):
        steps = max(2, int(np.hypot(x1 - x0, y1 - y0)))
        for t in np.linspace(0.0, 1.0, steps):
            cx, cy = x0 + t * (x1 - x0), y0 + t * (y1 - y0)
            mask |= (xx - cx) ** 2 + (yy - cy) ** 2 <= radius**2
    img[mask] = rgb


def _jagged(start: tuple[float, float], end: tuple[float, float], n: int, jitter: float, rng: np.random.Generator):
    t = np.linspace(0.0, 1.0, n)[:, None]
    pts = (1 - t) * np.asarray(start) + t * np.asarray(end)
    normal = np.array([-(end[1] - start[1]), end[0] - start[0]], dtype=np.float64)
    normal /= np.linalg.norm(normal)
    offsets = rng.uniform(-jitter, jitter, size=(n, 1))
    offsets[0] = offsets[-1] = 0.0
    return pts + offsets * normal


def cracked_skin(rgb: tuple[int, int, int], seed: int) -> np.ndarray:
    """A face texture with one bold crack across it plus two branches.

    The main crack is ~15% of the face wide: about 2 px in the 640 px overview
    (16 px per item) and bold in the wrist camera. At 224 px an item is only
    ~5 px, so cracks are not visible there from the standard overview pose.
    """
    rng = np.random.default_rng(seed)
    s = SKIN_PX
    img = np.empty((s, s, 3), dtype=np.uint8)
    img[:] = rgb
    # Subtle shading noise so the face does not look flat.
    noise = rng.normal(0.0, 6.0, size=(s, s, 1))
    img[:] = np.clip(img.astype(np.float64) + noise, 0, 255).astype(np.uint8)

    main = _jagged((0.0, s * 0.18), (s, s * 0.82), n=9, jitter=s * 0.08, rng=rng)
    _stamp_polyline(img, main, radius=s * 0.075, rgb=CRACK_RGB)
    for idx in (3, 6):
        start = tuple(main[idx])
        end = (start[0] + rng.uniform(-0.3, 0.3) * s, start[1] + rng.choice([-1, 1]) * 0.35 * s)
        _stamp_polyline(img, _jagged(start, end, n=5, jitter=s * 0.05, rng=rng), radius=s * 0.045, rgb=CRACK_RGB)
    return img


def belt_texture() -> np.ndarray:
    """Dark rubber with one lighter cleat line per tile, so belt motion is visible.

    One tile is one texture repeat; the belt wraps by exactly one repeat so the
    jump is invisible (see ``conveyor.py``).
    """
    img = np.empty((BELT_PX, BELT_PX, 3), dtype=np.uint8)
    img[:] = (38, 40, 44)
    rng = np.random.default_rng(7)
    img[:] = np.clip(img.astype(np.float64) + rng.normal(0.0, 3.0, size=(BELT_PX, BELT_PX, 1)), 0, 255).astype(
        np.uint8
    )
    band = BELT_PX // 6
    img[:band, :] = (92, 96, 102)
    return img


def reject_texture() -> np.ndarray:
    """Black and yellow hazard stripes for the reject bin walls."""
    s = 64
    yy, xx = np.mgrid[0:s, 0:s]
    stripes = ((xx + yy) // 16) % 2 == 0
    img = np.empty((s, s, 3), dtype=np.uint8)
    img[stripes] = (230, 180, 20)
    img[~stripes] = (25, 25, 25)
    return img


def main() -> None:
    """Write every conveyor_sort texture into the scene's assets directory."""
    if set(ITEM_COLORS) != set(ITEM_COLOR_NAMES):
        msg = f"Texture colors {sorted(ITEM_COLORS)} do not match conveyor.ITEM_COLORS {sorted(ITEM_COLOR_NAMES)}"
        raise SystemExit(msg)
    OUT.mkdir(parents=True, exist_ok=True)
    for idx, (name, rgb) in enumerate(ITEM_COLORS.items()):
        _write_png(OUT / f"cracked_{name}.png", cracked_skin(rgb, seed=100 + idx))
    _write_png(OUT / "belt.png", belt_texture())
    _write_png(OUT / "reject_stripes.png", reject_texture())
    for name, (text, rgb) in LABELS.items():
        _write_png(OUT / f"label_{name}.png", label_texture(text, rgb))
    write_meshes()
    (OUT.parent / "conveyor_items.xml").write_text(items_xml())
    print(f"Wrote textures to {OUT}")


if __name__ == "__main__":
    main()
