name: Library

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - &set-up-python
        name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"

      - name: Run prek
        uses: j178/prek-action@e98a699c41eb69ab013a45817a0406469a748f8d # v2
        with:
          prek-version: "0.4.0"
          extra-args: --all-files

  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - *checkout

      - *set-up-python

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.8.8"

      - name: Install dependencies
        run: uv sync --frozen --extra tests --extra robots --extra transport

      - name: Run python unit tests
        run: uv run pytest tests/unit
