name: Library

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - &set-up-python
        name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Run prek
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2
        with:
          extra-args: --all-files

  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - *checkout

      - *set-up-python

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.8.8"

      - name: Install dependencies
        run: uv sync --frozen --extra tests --extra robots

      - name: Run python unit tests
        run: uv run pytest tests/unit
